### ISSUE TITLE
Compilation error: ISR confict with Servo

### ISSUE THREAD

**Issue by gergelytakacs** [gergelytakacs/AutomationShield#143]
Conflict with Timer1 even though servo not used ???
```
libraries\Servo\avr\Servo.cpp.o (symbol from plugin): In function `ServoCount':

(.text+0x0): multiple definition of `__vector_11'

sketch\OptoShield_PIDAuto.ino.cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Uno.
```

**Comment by gergelytakacs** [comment]
@TiborKonkoly and @lukasvadovic2 please read:

I had to come back to the Sampling module, since changing to Timer2 on Uno broke other shields because of a clash between PWM and the Timer2 (Opto, Heat etc.).

However, I've noticed another bug. If you separate the BOB module into a header and implementation file (h/cpp) like you should, a BOB object file is created. This invokes the Servo library, creating an object file for it to cache. Now, when you compile for the other boards like Opto, they use Timer1, but there is the cached file for Servo and you'll get a redefinition for the ISR...

Solution: only create a heder (no cpp) for BOB. Move stuff from the cpp file to h, so it does not get built independently.
